apiVersion: apps/v1
kind: Deployment
metadata: 
  name: just-speak-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: just-speak
  template: 
    metadata: 
      labels: 
        app: just-speak
    resources: 
      requests: 
        cpu: 512m
        memory: 128Mi
    spec: 
      containers: 
        - 
          image: "codingnightmare/just-speak:v1"
          name: just-speak
          ports: 
            - 
              containerPort: 3000
